wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.0
    t:
      4: 3.9.0
      5: 0.10.22
      8:
      - 1
      - 5
